# docker build -f .devcontainer/Dockerfile.dev -t webis/longeval-topic-baseline:dev-0.0.1 .
FROM ubuntu:jammy

RUN apt-get update && apt-get install -y python3 python3-pip

ADD requirements.txt /

# Install dependencies and ensure pyterrier resources are cached
RUN pip3 install -r /requirements.txt \
	&& rm /requirements.txt

